services:
  julgate:
    environment:
      JULGATE_ADMIN_PASSWORD: ""
      JULGATE_ADMIN_PASSWORD_FILE: /run/secrets/julgate_admin_password
      JULGATE_CREDENTIAL_KEY: ""
      JULGATE_CREDENTIAL_KEY_FILE: /run/secrets/julgate_credential_key
    secrets:
      - julgate_admin_password
      - julgate_credential_key

secrets:
  julgate_admin_password:
    file: ${JULGATE_ADMIN_PASSWORD_SECRET_FILE:-./secrets/julgate_admin_password}
  julgate_credential_key:
    file: ${JULGATE_CREDENTIAL_KEY_SECRET_FILE:-./secrets/julgate_credential_key}
